/**
 * Bulk-insert ~44 AI tools researched from the web.
 * Run via:  npx tsx scripts/scrape-tools.ts
 * Requires: SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY in .env.local
 */
import { config } from "dotenv";
config({ path: ".env.local" });
config();
import { createClient } from "@supabase/supabase-js";
import type { Database } from "../app/types/database";

const supabase = createClient<Database>(
  process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL ?? "",
  process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
);

// Category slug used by the data → slug in our categories table
const CAT_MAP: Record<string, string> = {
  "chat-assistants":  "chat-assistants",
  "code-assistants":  "coding",
  "image-generation": "image-generation",
  "video-generation": "video",
  "writing-tools":    "writing",
  "search-research":  "search-research",
  "agent-automation": "automation",
  "developer-tools":  "infrastructure",
};

const TOOLS = [
  // ── Chat / LLM interfaces ────────────────────────────────────────────────
  {
    slug: "gemini",
    name: "Gemini",
    tagline: "Google's multimodal AI assistant with deep Search and Workspace integration",
    website_url: "https://gemini.google.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 19.99,
    audience_fit: "both",
    model_provider: "Google",
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Native Google Search grounding", "2M token context window", "Free tier with Deep Research", "Multimodal image, video, audio input", "Tight Google Workspace integration"],
    category_slug: "chat-assistants",
    overview_general: "Gemini is Google's flagship AI assistant that answers questions, writes content, and helps you get things done directly inside Google Docs, Gmail, and Search. The free tier includes access to Deep Research and Gemini Live voice mode. It's used by millions for everyday tasks, coding help, and creative projects.",
    overview_technical: "Built on Google's Gemini 2.x model family, it offers a 2M-token context window and a REST/gRPC API via Google AI Studio and Vertex AI. Supports function calling, structured JSON output, and code execution. Integrates with Google Cloud services and the Gemini CLI.",
  },
  {
    slug: "microsoft-copilot",
    name: "Microsoft Copilot",
    tagline: "AI assistant built into Windows, Edge, and Microsoft 365 for everyday productivity",
    website_url: "https://copilot.microsoft.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 20,
    audience_fit: "both",
    model_provider: "OpenAI",
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Deeply embedded in Windows 11 and Microsoft 365", "Free web access", "DALL-E image generation included", "M365 Copilot integrates with Word, Excel, Teams", "GPT-4o powered"],
    category_slug: "chat-assistants",
    overview_general: "Microsoft Copilot is an AI assistant available for free on the web and built into Windows 11, Edge, and Microsoft 365 apps. It helps with writing, summarizing emails, generating images, and answering questions using GPT-4o. A Copilot Pro subscription unlocks priority access and deeper Office integration.",
    overview_technical: "Powered by OpenAI's GPT-4o with Bing grounding for real-time web search. Microsoft 365 Copilot adds Graph-connected context (emails, documents, calendar) at $30/user/month. Copilot Studio enables building custom agents with Power Platform integration and an API surface.",
  },
  {
    slug: "grok",
    name: "Grok",
    tagline: "xAI's witty, real-time AI assistant with direct access to X platform data",
    website_url: "https://grok.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 30,
    audience_fit: "both",
    model_provider: "xAI",
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Real-time X/Twitter data access", "Integrated image generation via Aurora", "256K token context on SuperGrok Heavy", "Built-in voice mode", "Grok 4 with extended reasoning"],
    category_slug: "chat-assistants",
    overview_general: "Grok is Elon Musk's AI assistant from xAI, known for its real-time awareness of what's trending on X. The free tier gives basic access; SuperGrok ($30/month) unlocks the flagship Grok 4 model with extended memory and image generation. Popular with X power users and researchers tracking current events.",
    overview_technical: "Grok 4 features a 128K–256K context window. The xAI API offers OpenAI-compatible endpoints at $3/M input and $15/M output tokens for grok-4. Supports function calling, structured outputs, and live web search grounding.",
  },
  {
    slug: "meta-ai",
    name: "Meta AI",
    tagline: "Free AI assistant from Meta, powered by Llama, embedded in WhatsApp, Instagram, and Facebook",
    website_url: "https://meta.ai",
    logo_url: null,
    pricing_tier: "free",
    has_free_tier: true,
    pricing_starts_at: null,
    audience_fit: "non_technical",
    model_provider: "Meta",
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Completely free, no paid tier", "Accessible inside WhatsApp, Instagram, Messenger, Facebook", "Powered by Llama 4", "Real-time web search", "Image generation included"],
    category_slug: "chat-assistants",
    overview_general: "Meta AI is a completely free AI assistant from Meta, accessible through WhatsApp, Instagram, Facebook, and Messenger with no account required. It answers questions, helps with writing, and generates images — all at no cost. With billions of people already using Meta's apps, it has the widest consumer reach of any AI assistant.",
    overview_technical: "Powered by Llama 4, Meta's latest open-weights model family. Meta AI itself is a consumer product with no public API, but the underlying Llama 4 models are available on Hugging Face and through third-party inference providers. Integrates real-time web search results.",
  },
  {
    slug: "poe",
    name: "Poe",
    tagline: "Quora's multi-model AI hub for chatting with GPT-4, Claude, Gemini, and hundreds more",
    website_url: "https://poe.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 4.99,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2022,
    hq_country: "US",
    key_strengths: ["Access to 100+ AI models in one app", "Create and share custom chatbots", "Daily free messages across models", "Bot monetization for creators", "Mobile-first design"],
    category_slug: "chat-assistants",
    overview_general: "Poe is Quora's AI platform that lets you chat with GPT-4, Claude, Gemini, Llama, and hundreds of other models all in one place. The free plan gives limited daily messages; Poe Pro ($19.99/month) unlocks 1M compute points for heavy use. Creators can build and monetize custom bots.",
    overview_technical: "Poe aggregates models from OpenAI, Anthropic, Google, Meta, Mistral, and open-source providers via a unified API. Developers can build custom bots using the Poe Bot API with server-sent events for streaming responses.",
  },
  {
    slug: "le-chat",
    name: "Le Chat (Mistral)",
    tagline: "Mistral's fast European AI assistant with strong open-source model roots",
    website_url: "https://chat.mistral.ai",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 14.99,
    audience_fit: "both",
    model_provider: "Mistral",
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2023,
    hq_country: "FR",
    key_strengths: ["GDPR-compliant EU-hosted option", "Access to Mistral's open and proprietary models", "Extremely fast inference", "Strong multilingual support", "Open-weight models via API"],
    category_slug: "chat-assistants",
    overview_general: "Le Chat is Mistral AI's chat interface, offering a fast, privacy-friendly alternative to US-based AI assistants. The free tier gives unlimited access to Mistral's models, while the Pro plan ($14.99/month) adds web search, document processing, and collaboration features. Popular with European businesses seeking GDPR compliance.",
    overview_technical: "Backed by Mistral's model family including Mistral Large, Mistral Small, and open-weight Mixtral models. The Mistral API is OpenAI-compatible with function calling, JSON mode, and embeddings. Models can be deployed on-premises via self-hosting open-weight checkpoints from Hugging Face.",
  },
  {
    slug: "huggingchat",
    name: "HuggingChat",
    tagline: "Open-source chat interface by Hugging Face for testing community models for free",
    website_url: "https://huggingface.co/chat",
    logo_url: null,
    pricing_tier: "free",
    has_free_tier: true,
    pricing_starts_at: null,
    audience_fit: "technical",
    model_provider: null,
    open_source: true,
    self_hostable: true,
    api_available: false,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Entirely free, no credit card", "Access to community open-weight models", "Open-source codebase self-hostable", "Web search grounding", "Supports Llama, Mistral, Zephyr, and more"],
    category_slug: "chat-assistants",
    overview_general: "HuggingChat is Hugging Face's free, open-source chat interface for experimenting with the latest open-weight models like Llama, Mistral, and Zephyr. It's the easiest way to test community models without setting up any infrastructure. No account required for basic use.",
    overview_technical: "The chat-ui codebase is fully open source on GitHub and self-hostable. It connects to Hugging Face's Inference API backends, supporting text-generation-inference (TGI) as the underlying serving engine. Developers can swap models via environment variables and add custom tools.",
  },
  {
    slug: "deepseek",
    name: "DeepSeek",
    tagline: "Chinese open-source frontier AI with reasoning models that rival GPT-4 at a fraction of the cost",
    website_url: "https://chat.deepseek.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: null,
    audience_fit: "both",
    model_provider: "DeepSeek",
    open_source: true,
    self_hostable: true,
    api_available: true,
    founded_year: 2023,
    hq_country: "CN",
    key_strengths: ["MIT-licensed open weights (DeepSeek-R1, V3)", "API from $0.27/M input tokens", "Context caching reduces costs 90%", "Chain-of-thought reasoning model", "Rivals GPT-4 at dramatically lower cost"],
    category_slug: "chat-assistants",
    overview_general: "DeepSeek is a Chinese AI lab that released DeepSeek-R1 and DeepSeek-V3 — frontier reasoning models with MIT-licensed open weights that shocked the industry with their quality relative to cost. The chat interface is free; the API is among the cheapest for advanced reasoning tasks. Self-hosting is possible on consumer-grade hardware via quantized versions.",
    overview_technical: "DeepSeek-V3 is a 671B MoE model; DeepSeek-R1 is a reasoning model with extended chain-of-thought. API is OpenAI-compatible, priced at $0.27/M input and $1.10/M output for V3. Supports function calling, JSON mode, and FIM for code. Weights available on Hugging Face for self-hosting.",
  },

  // ── Code assistants ──────────────────────────────────────────────────────
  {
    slug: "windsurf",
    name: "Windsurf",
    tagline: "Agentic AI code editor with Cascade flows that plan, edit, and run code autonomously",
    website_url: "https://windsurf.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 15,
    audience_fit: "technical",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2021,
    hq_country: "US",
    key_strengths: ["Cascade agent flows for multi-step autonomous coding", "Full codebase context awareness", "VS Code fork with native AI", "Multi-file editing in one session", "Free tier with 5 Flow Actions/day"],
    category_slug: "code-assistants",
    overview_general: "Windsurf (formerly Codeium) is an AI-native code editor where an agent called Cascade can plan a feature, write code across multiple files, run tests, and fix errors without manual prompting. The free plan gives daily AI credits; Pro ($15/month) unlocks unlimited flows. It's a direct competitor to Cursor.",
    overview_technical: "Built as a VS Code fork with a proprietary Cascade agent runtime supporting tool use, terminal execution, and browser preview. Connects to Claude, GPT-4o, and Gemini backends with automatic model routing. Enterprise deployments offer VPC isolation. Acquired by OpenAI in 2025 for ~$3B.",
  },
  {
    slug: "tabnine",
    name: "Tabnine",
    tagline: "Enterprise AI code assistant that runs privately inside your VPC or on-premises",
    website_url: "https://tabnine.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 9,
    audience_fit: "technical",
    model_provider: null,
    open_source: false,
    self_hostable: true,
    api_available: false,
    founded_year: 2018,
    hq_country: "US",
    key_strengths: ["Air-gapped and on-premises deployment", "Trained only on permissive-license code", "Supports 30+ IDEs", "Team-trained models on your codebase", "SOC 2 Type II certified"],
    category_slug: "code-assistants",
    overview_general: "Tabnine is an AI coding assistant built for enterprises that need code to stay private. Unlike cloud-first tools, Tabnine can run fully on-premises or in your VPC, ensuring source code never leaves your environment. It offers autocomplete, chat, and code generation trained only on permissively-licensed code.",
    overview_technical: "Supports SaaS, VPC, on-premises, and air-gapped deployments. IDE plugins for VS Code, JetBrains, Visual Studio, and 30+ others. Teams can fine-tune models on their own codebase for context-aware suggestions. Enterprise tier ($39/user/month) includes SSO, audit logs, and dedicated infrastructure.",
  },
  {
    slug: "codeium",
    name: "Codeium",
    tagline: "Free AI code autocomplete and chat with zero data retention and broad IDE support",
    website_url: "https://codeium.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 15,
    audience_fit: "technical",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2021,
    hq_country: "US",
    key_strengths: ["Unlimited free autocomplete for individuals", "70+ IDE and editor integrations", "Zero data retention on free tier", "Fast inline completions", "Supports 70+ programming languages"],
    category_slug: "code-assistants",
    overview_general: "Codeium offers unlimited free AI code autocomplete and an in-editor chat assistant for individual developers. It plugs into over 70 editors including VS Code, JetBrains, Vim, and Emacs. Unlike many competitors, the individual plan is genuinely free with no usage caps.",
    overview_technical: "Codeium's backend runs proprietary models optimized for low-latency inline completion. The extension communicates via a local Language Server Protocol bridge. Enterprise plans support SSO, audit logs, and on-premises deployment.",
  },
  {
    slug: "amazon-q-developer",
    name: "Amazon Q Developer",
    tagline: "AWS's AI developer assistant for writing, explaining, and transforming code in the cloud",
    website_url: "https://aws.amazon.com/q/developer",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 19,
    audience_fit: "technical",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Deep AWS Console and service integration", "Automated Java/Python code transformation", "Security vulnerability scanning", "Free tier with 50 requests/month", "Inline chat in VS Code and JetBrains"],
    category_slug: "code-assistants",
    overview_general: "Amazon Q Developer is AWS's AI coding assistant that answers questions about your AWS environment, writes code in your IDE, and can automatically upgrade legacy Java code. The free tier covers 50 monthly interactions; Pro ($19/user/month) adds unlimited use and advanced security scanning.",
    overview_technical: "Integrates with VS Code, JetBrains, Visual Studio, and the AWS Console. Uses Amazon's custom Titan models with private endpoint options via AWS PrivateLink. Security scans integrate with AWS Security Hub.",
  },
  {
    slug: "aider",
    name: "Aider",
    tagline: "Terminal-based AI pair programmer with native Git integration and any-LLM support",
    website_url: "https://aider.chat",
    logo_url: null,
    pricing_tier: "free",
    has_free_tier: true,
    pricing_starts_at: null,
    audience_fit: "technical",
    model_provider: null,
    open_source: true,
    self_hostable: true,
    api_available: false,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Free and open source (MIT)", "Auto-commits changes with descriptive messages", "Connects to any LLM (Claude, GPT-4, DeepSeek, local)", "Whole-repo context via tree-sitter map", "4M+ installs on PyPI"],
    category_slug: "code-assistants",
    overview_general: "Aider is a free, open-source AI coding assistant that runs in your terminal. You describe changes in plain English and it edits your files, then automatically commits the result with a descriptive Git message. It works with any LLM — you pay only for API usage.",
    overview_technical: "Uses a repo-map built from tree-sitter AST parsing to give the LLM precise context about codebase structure. Supports Claude, GPT-4, DeepSeek, Gemini, and local Ollama models. Written in Python; installable via pip. Architect + editor workflow separates planning from implementation.",
  },
  {
    slug: "continue-dev",
    name: "Continue",
    tagline: "Open-source AI code assistant for VS Code and JetBrains with bring-your-own-model flexibility",
    website_url: "https://continue.dev",
    logo_url: null,
    pricing_tier: "free",
    has_free_tier: true,
    pricing_starts_at: null,
    audience_fit: "technical",
    model_provider: null,
    open_source: true,
    self_hostable: true,
    api_available: false,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Open source (Apache 2.0)", "Supports VS Code and JetBrains natively", "Autocomplete, chat, edit, and agent modes", "Connect any LLM via config file", "Self-hostable control plane for teams"],
    category_slug: "code-assistants",
    overview_general: "Continue is a free, open-source AI coding assistant that installs as an extension in VS Code or JetBrains. Unlike proprietary tools, you configure it to use any LLM provider — Claude, OpenAI, local Ollama, or your company's self-hosted model.",
    overview_technical: "Apache-licensed on GitHub with 26K+ stars. Communicates with LLM providers via configurable adapters in config.json. Supports slash commands, context providers (files, URLs, docs, Git diff), and custom tools. Continue Hub provides a registry of shareable configs for teams.",
  },
  {
    slug: "replit-ai",
    name: "Replit AI",
    tagline: "Browser-based AI coding environment for building and deploying apps without any setup",
    website_url: "https://replit.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 25,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2016,
    hq_country: "US",
    key_strengths: ["Zero-setup browser-based IDE", "One-click deploy to production", "AI agent generates full apps from prompts", "Built-in database, auth, and hosting", "Huge library of templates and forks"],
    category_slug: "code-assistants",
    overview_general: "Replit is a browser-based coding platform where you can build, run, and deploy apps without installing anything. Its AI agent can scaffold entire applications from a text prompt, then help you iterate. Popular with students, hobbyists, and rapid prototypers.",
    overview_technical: "Replit runs containerized environments per project with persistent filesystem state. The AI agent uses Claude and GPT-4 models with full tool use over the filesystem and shell. Deployments run on Replit's infrastructure as autoscaling web services. Nix-based environment configuration lets advanced users customize runtimes.",
  },

  // ── Image generation ─────────────────────────────────────────────────────
  {
    slug: "dall-e",
    name: "DALL-E 3",
    tagline: "OpenAI's text-to-image model with precise prompt adherence built into ChatGPT",
    website_url: "https://openai.com/dall-e-3",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: false,
    pricing_starts_at: 20,
    audience_fit: "both",
    model_provider: "OpenAI",
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2021,
    hq_country: "US",
    key_strengths: ["Excellent prompt adherence", "Available directly in ChatGPT Plus", "API access for developers", "Handles long natural language prompts", "Safe content policies with artist opt-out"],
    category_slug: "image-generation",
    overview_general: "DALL-E 3 is OpenAI's image generation model, accessible through ChatGPT Plus and the OpenAI API. It excels at following detailed text prompts accurately, making it easy to generate specific compositions without prompt engineering tricks.",
    overview_technical: "Available via the OpenAI Images API at $0.04–$0.12 per image depending on resolution (1024x1024 to 1792x1024). Supports in-painting and editing via gpt-image-1. Rate-limited per API key; integrates with the Assistants API for tool use.",
  },
  {
    slug: "adobe-firefly",
    name: "Adobe Firefly",
    tagline: "Adobe's commercially safe AI image generator trained on licensed and public domain content",
    website_url: "https://firefly.adobe.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 9.99,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Trained on licensed content — commercially safe output", "Deep Photoshop and Illustrator integration", "Generative Fill for in-painting", "Vector and texture generation", "IP indemnification for enterprise users"],
    category_slug: "image-generation",
    overview_general: "Adobe Firefly is Adobe's family of AI creative models designed for commercial use — trained on Adobe Stock, openly licensed content, and public domain images so the output is safe to use in client work. Generative Fill in Photoshop is powered by Firefly. A free plan gives 25 monthly generative credits.",
    overview_technical: "Firefly models are embedded in Photoshop, Illustrator, Express, and Premiere Pro as native features. The Firefly Services API exposes text-to-image, generative fill, style transfer, and object compositing endpoints. Adobe offers IP indemnification for enterprise Firefly API customers.",
  },
  {
    slug: "stable-diffusion",
    name: "Stable Diffusion",
    tagline: "Pioneering open-source text-to-image model that runs locally on consumer GPUs",
    website_url: "https://stability.ai",
    logo_url: null,
    pricing_tier: "free",
    has_free_tier: true,
    pricing_starts_at: null,
    audience_fit: "technical",
    model_provider: "StabilityAI",
    open_source: true,
    self_hostable: true,
    api_available: true,
    founded_year: 2022,
    hq_country: "UK",
    key_strengths: ["Free open weights run locally", "Massive ecosystem of fine-tuned models (LoRA, ControlNet)", "No content censorship when self-hosted", "Runs on 8GB VRAM consumer GPU", "Largest community of custom models on CivitAI"],
    category_slug: "image-generation",
    overview_general: "Stable Diffusion is the foundational open-source text-to-image model released by Stability AI in 2022. Because the weights are free, anyone can run it locally — meaning no subscriptions, no content restrictions, and full privacy. A vast ecosystem of fine-tuned models, LoRAs, and tools like AUTOMATIC1111 and ComfyUI have grown around it.",
    overview_technical: "Latent diffusion architecture using a VAE, text encoder (CLIP), and U-Net denoiser. SDXL and SD 3.5 are the latest generations. Runs via AUTOMATIC1111, ComfyUI, or InvokeAI on 8GB+ VRAM. Stability AI offers a REST API with per-credit pricing. ControlNet extensions enable structural conditioning from depth maps and poses.",
  },
  {
    slug: "ideogram",
    name: "Ideogram",
    tagline: "AI image generator that actually gets text right — built for logos, posters, and typography",
    website_url: "https://ideogram.ai",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 8,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Best-in-class legible text rendering in images", "Built-in Canvas editor", "Style presets for brand consistency", "Magic Prompt auto-enhancer", "API access for developers"],
    category_slug: "image-generation",
    overview_general: "Ideogram is an AI image generator that solved one of the field's hardest problems: rendering legible, accurate text inside images. It's the go-to tool for creating logos, posters, t-shirt designs, and social graphics where typography matters. The free tier gives 10 slow generations per day.",
    overview_technical: "Ideogram 3.0 features native typography-aware generation. The API offers text-to-image, image editing, and upscaling endpoints with Base64 or URL responses. Supports style references, aspect ratio control, and negative prompts. REST API with per-image credit billing.",
  },
  {
    slug: "leonardo-ai",
    name: "Leonardo.ai",
    tagline: "AI image and video platform with fine-tuning for game assets, characters, and concept art",
    website_url: "https://leonardo.ai",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 10,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2022,
    hq_country: "AU",
    key_strengths: ["150 free tokens daily on free tier", "Fine-tune models on your own dataset", "Specialized game-asset and character models", "Canvas editor for in-painting and outpainting", "FLUX and Phoenix model access"],
    category_slug: "image-generation",
    overview_general: "Leonardo.ai is an AI creative platform popular with game developers, concept artists, and product designers. It offers 150 free tokens daily and access to specialized models for characters, environments, and textures. Custom model training lets studios fine-tune on their own art style.",
    overview_technical: "Powered by Stable Diffusion checkpoints, FLUX, and Leonardo's proprietary Phoenix model. Fine-tuning uses DreamBooth-style training on uploaded datasets. REST API supports text-to-image, image-to-image, inpainting, and upscaling.",
  },
  {
    slug: "flux",
    name: "FLUX",
    tagline: "Black Forest Labs' open image model rivaling Midjourney at a fraction of the cost",
    website_url: "https://blackforestlabs.ai",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: null,
    audience_fit: "technical",
    model_provider: null,
    open_source: true,
    self_hostable: true,
    api_available: true,
    founded_year: 2024,
    hq_country: "DE",
    key_strengths: ["Open weights (FLUX.1 Dev/Schnell, Apache 2.0)", "State-of-the-art photorealism", "FLUX Pro API via BFL and Replicate", "10–20% of Midjourney cost via API", "Excellent anatomy and hand rendering"],
    category_slug: "image-generation",
    overview_general: "FLUX by Black Forest Labs is the leading open-source image generation model, producing photorealistic results that rival Midjourney and DALL-E 3. The FLUX.1 Schnell and Dev models are free to run locally; FLUX Pro is available via API. Created by former Stable Diffusion researchers.",
    overview_technical: "Uses a novel rectified flow transformer (DiT) architecture rather than the classic U-Net. FLUX.1 Schnell (Apache 2.0) runs in 1–4 steps; FLUX.1 Dev (non-commercial) in 28 steps. Available on Replicate, fal.ai, and the BFL API. Runs on 24GB VRAM for full quality; quantized versions work on 12GB.",
  },

  // ── Video generation ─────────────────────────────────────────────────────
  {
    slug: "pika",
    name: "Pika",
    tagline: "Easy-to-use AI video generator that turns text and images into polished short clips",
    website_url: "https://pika.art",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 8,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Beginner-friendly interface", "Modify specific objects in a video (Modify Region)", "Expand video canvas (Pikaffects)", "Animate static images", "Daily free credits"],
    category_slug: "video-generation",
    overview_general: "Pika is an AI video generator focused on accessibility and creativity. It lets anyone turn text prompts or still images into short video clips with smooth motion. Features like Modify Region let you change specific parts of a video while Pikaffects adds cinematic effects.",
    overview_technical: "Pika's models are proprietary and cloud-only. Paid plans ($8/month+) offer higher resolution, longer clips, and watermark-free downloads. All inference is server-side with per-generation credit consumption.",
  },
  {
    slug: "luma-dream-machine",
    name: "Luma Dream Machine",
    tagline: "Luma AI's high-quality video generator with photorealistic motion and camera controls",
    website_url: "https://lumalabs.ai/dream-machine",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 9.99,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Photorealistic motion quality", "Image-to-video with character consistency", "Camera movement controls", "API access for developers", "30 free generations per month"],
    category_slug: "video-generation",
    overview_general: "Dream Machine by Luma AI generates smooth, photorealistic videos from text prompts or reference images. It's praised for realistic motion physics and consistent character appearance across frames. The free plan provides 30 monthly generations.",
    overview_technical: "Built on Luma's Ray2 video diffusion model. The Luma AI API supports text-to-video and image-to-video endpoints with controllable camera movements (pan, tilt, orbit). Uses credit-based billing; each 5-second 720p generation costs ~50 credits.",
  },
  {
    slug: "kling-ai",
    name: "Kling AI",
    tagline: "Kuaishou's video generation model with up to 3-minute clips and strong human motion",
    website_url: "https://klingai.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 6.99,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2024,
    hq_country: "CN",
    key_strengths: ["$0.07/second of video — 65% cheaper than Runway", "Up to 3-minute video generation", "Strong human motion rendering", "API for integration", "Text-to-video and image-to-video"],
    category_slug: "video-generation",
    overview_general: "Kling AI is a video generation platform from Kuaishou that has emerged as a strong price-performance leader among AI video tools. At $6.99/month, it generates up to 3-minute videos with smooth character motion. Popular for short-form social media content and product demo videos.",
    overview_technical: "Kling's API offers text-to-video and image-to-video endpoints with per-second billing at approximately $0.07/second. Supports 720p and 1080p output with duration control. REST API with async job polling.",
  },
  {
    slug: "hailuo-ai",
    name: "Hailuo AI",
    tagline: "MiniMax's video model with ultra-smooth character motion and subject reference support",
    website_url: "https://hailuoai.video",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 14.99,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2023,
    hq_country: "CN",
    key_strengths: ["Natural character movements", "Subject reference for consistent characters", "Competitive API pricing", "6-second clips with realistic physics", "Enhanced motion rendering in v2.3"],
    category_slug: "video-generation",
    overview_general: "Hailuo AI is MiniMax's text-to-video platform, notable for producing natural-looking human character movement. At $14.99/month, it competes with Kling and Runway for short-form video creation.",
    overview_technical: "Powered by MiniMax's video-01 model. The API supports text-to-video and image-to-video with resolution control up to 1080p. Subject reference input allows consistent character identity across multiple generations.",
  },
  {
    slug: "sora",
    name: "Sora",
    tagline: "OpenAI's cinematic AI video model for generating long, high-resolution videos from text",
    website_url: "https://openai.com/sora",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: false,
    pricing_starts_at: 20,
    audience_fit: "both",
    model_provider: "OpenAI",
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2024,
    hq_country: "US",
    key_strengths: ["Up to 1080p and 20-second videos", "Cinematic camera movement controls", "Storyboard mode for sequenced shots", "Re-cut and extend videos", "Included with ChatGPT Plus"],
    category_slug: "video-generation",
    overview_general: "Sora is OpenAI's text-to-video model, capable of generating high-definition videos up to 20 seconds long with cinematic quality. Available to ChatGPT Plus subscribers ($20/month), it's designed for filmmakers, content creators, and marketers who need polished video content from text.",
    overview_technical: "Sora uses a spacetime patch transformer architecture trained on video and image data. Available through the Sora web interface included in ChatGPT Plus and Pro plans. Monthly generation limits apply based on subscription tier.",
  },

  // ── Writing / productivity ────────────────────────────────────────────────
  {
    slug: "jasper",
    name: "Jasper",
    tagline: "AI writing platform for marketing teams with brand voice controls and campaign workflows",
    website_url: "https://jasper.ai",
    logo_url: null,
    pricing_tier: "paid",
    has_free_tier: false,
    pricing_starts_at: 39,
    audience_fit: "non_technical",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2021,
    hq_country: "US",
    key_strengths: ["Brand Voice training locks in your tone", "50+ specialized marketing templates", "Campaigns feature for multi-asset generation", "Integrates with Surfer SEO and Google Docs", "Team collaboration workspace"],
    category_slug: "writing-tools",
    overview_general: "Jasper is an AI writing platform built specifically for marketing teams. It lets you train it on your brand guidelines and tone, so every piece of content sounds authentically like your company. It generates blog posts, ads, social copy, and emails with specialized marketing templates.",
    overview_technical: "Uses a proprietary model layer on top of GPT-4 and Claude, adding brand voice embedding and template-specific fine-tuning. The Jasper API allows programmatic content generation for CMS integrations. Campaigns orchestrate multi-step content generation across formats.",
  },
  {
    slug: "copy-ai",
    name: "Copy.ai",
    tagline: "AI-powered GTM platform that automates sales and marketing workflows end-to-end",
    website_url: "https://copy.ai",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 49,
    audience_fit: "non_technical",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2020,
    hq_country: "US",
    key_strengths: ["Go-to-Market AI Workflows for sales sequences", "CRM enrichment automation", "90+ copywriting templates", "Unlimited words on all paid plans", "Integrates with HubSpot and Salesforce"],
    category_slug: "writing-tools",
    overview_general: "Copy.ai has evolved from an AI copywriting tool into a full go-to-market platform. It automates sales email sequences, lead enrichment, and marketing content at scale. The free plan gives 2,000 words per month; paid plans ($49/month) include unlimited words and workflow automation.",
    overview_technical: "Copy.ai Workflows orchestrate multi-step AI pipelines with conditional logic, CRM integrations, and web research capabilities. Connects to HubSpot, Salesforce, and Apollo. Built on top of GPT-4 and Claude. API available for enterprise customers to trigger workflows programmatically.",
  },
  {
    slug: "writesonic",
    name: "Writesonic",
    tagline: "AI writing and SEO platform for long-form content, product descriptions, and article generation",
    website_url: "https://writesonic.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 20,
    audience_fit: "non_technical",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2021,
    hq_country: "US",
    key_strengths: ["Chatsonic with real-time Google Search access", "Bulk article generation", "AI Article Writer with SEO scoring", "GPT-4 and Claude powered", "200+ content templates"],
    category_slug: "writing-tools",
    overview_general: "Writesonic is an AI content platform covering blog posts, product descriptions, landing pages, and ads. Its Chatsonic assistant adds real-time Google Search to answers. An affordable entry point (from $20/month) and bulk generation features make it popular with content teams and SEO agencies.",
    overview_technical: "Writesonic uses GPT-4 and Claude 3 as backends with a proprietary SEO optimization layer. The Writesonic API exposes article generation, paraphrasing, and Chatsonic endpoints for CMS integration. Article Writer 6.0 automatically includes citations sourced from Google.",
  },
  {
    slug: "otter-ai",
    name: "Otter.ai",
    tagline: "Real-time meeting transcription and summary AI that works with Zoom, Teams, and Google Meet",
    website_url: "https://otter.ai",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 8.33,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2016,
    hq_country: "US",
    key_strengths: ["Joins Zoom/Teams/Meet as AI note-taker bot", "Real-time transcription during calls", "Auto-generated action items and summaries", "Speaker identification", "Searchable transcript archive"],
    category_slug: "writing-tools",
    overview_general: "Otter.ai automatically joins your Zoom, Teams, or Google Meet calls, transcribes the conversation in real time, and generates a summary with action items when the meeting ends. The free plan offers 600 minutes of transcription per month.",
    overview_technical: "Otter sends a bot participant to meetings via calendar integration. Transcription uses proprietary ASR models with speaker diarization. The Otter API enables pulling transcripts, summaries, and action items programmatically for CRM integration.",
  },
  {
    slug: "fireflies-ai",
    name: "Fireflies.ai",
    tagline: "AI meeting assistant that records, transcribes, and extracts insights from every conversation",
    website_url: "https://fireflies.ai",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 10,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2016,
    hq_country: "US",
    key_strengths: ["Unlimited storage on free tier", "Ask Fred AI to query meeting transcripts", "CRM sync to Salesforce and HubSpot", "Topic-based sentiment tracking", "Supports 60+ languages"],
    category_slug: "writing-tools",
    overview_general: "Fireflies.ai records, transcribes, and analyzes your meetings across Zoom, Teams, Meet, and 10+ other platforms. Ask Fred, the AI companion, questions about past meetings. The free tier includes unlimited storage — a notable differentiator.",
    overview_technical: "Fireflies joins meetings as a bot participant and uses proprietary ASR with speaker identification. The Fred AI layer uses an LLM to answer questions over the meeting transcript corpus. API supports pulling transcripts, summaries, topics, and sentiment scores per meeting.",
  },
  {
    slug: "descript",
    name: "Descript",
    tagline: "Video and podcast editor where you edit your recording by editing the transcript text",
    website_url: "https://descript.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 19,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2017,
    hq_country: "US",
    key_strengths: ["Edit video by editing transcript text", "Overdub AI voice cloning fills removed words", "Filler word removal in one click", "Screen recording built in", "Studio Sound AI noise removal"],
    category_slug: "writing-tools",
    overview_general: "Descript is a video and podcast editor with a unique interface: you edit media by editing the text transcript. Delete a sentence and the video cuts automatically. The Overdub feature clones your voice so you can type corrections that sound like you. Widely used by podcasters, YouTubers, and online course creators.",
    overview_technical: "Descript's transcription pipeline uses Whisper-based ASR with word-level timestamps. Overdub voice cloning trains a TTS model on ~10 minutes of your voice. Studio Sound uses neural audio enhancement. Desktop app on Mac and Windows with cloud project sync.",
  },

  // ── Search / research ─────────────────────────────────────────────────────
  {
    slug: "consensus",
    name: "Consensus",
    tagline: "AI search engine that finds and synthesizes evidence from 200M+ scientific papers",
    website_url: "https://consensus.app",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 9.99,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2022,
    hq_country: "US",
    key_strengths: ["Claim-verification with yes/no/mixed answers", "200M+ indexed scientific papers", "Consensus Meter visualizes evidence strength", "GPT-4 generated Copilot summaries", "Cites specific papers with DOI links"],
    category_slug: "search-research",
    overview_general: "Consensus is an AI search engine for scientific research that takes a unique approach: you ask a question and it finds relevant peer-reviewed papers, then tells you whether the evidence supports, contradicts, or is mixed on your claim. Used by students, doctors, and researchers.",
    overview_technical: "Uses semantic search over 200M+ papers indexed from Semantic Scholar and PubMed with a claim extraction model that identifies research conclusions. The Copilot feature uses GPT-4 to synthesize summaries. Free tier limited to 20 searches/month.",
  },
  {
    slug: "elicit",
    name: "Elicit",
    tagline: "AI research assistant for literature review that extracts structured data from scientific papers",
    website_url: "https://elicit.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 12,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2021,
    hq_country: "US",
    key_strengths: ["Extract specific columns of data from PDFs (e.g. sample sizes)", "125M+ indexed papers", "Used by 2M+ researchers", "Systematic review workflow", "Automated data extraction tables"],
    category_slug: "search-research",
    overview_general: "Elicit is an AI research assistant specifically designed for literature reviews. Rather than just summarizing papers, it extracts structured data — like sample sizes, interventions, and outcomes — from hundreds of PDFs into a table, saving weeks of manual work.",
    overview_technical: "Uses semantic search and an LLM extraction pipeline to populate user-defined columns from full paper text. The 125M+ paper corpus comes from Semantic Scholar. Paid plans allow larger paper batches, longer documents, and custom extraction prompts.",
  },
  {
    slug: "phind",
    name: "Phind",
    tagline: "AI search engine for developers that understands code, docs, and technical questions natively",
    website_url: "https://phind.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 20,
    audience_fit: "technical",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2022,
    hq_country: "US",
    key_strengths: ["Understands code and technical docs natively", "Cites Stack Overflow, GitHub, and official docs", "Phind-405B model for complex coding questions", "VS Code extension", "Pair programmer with iterative follow-ups"],
    category_slug: "search-research",
    overview_general: "Phind is an AI search engine designed specifically for developers. When you ask a coding question, it searches the web, reads documentation and GitHub repos, and gives you a sourced, working code answer — not a generic summary.",
    overview_technical: "Phind combines web search retrieval with code-specialized LLMs including Phind-405B (fine-tuned on coding tasks) and models from Claude and OpenAI. The VS Code extension allows inline coding assistance.",
  },
  {
    slug: "you-com",
    name: "You.com",
    tagline: "Privacy-first AI search engine with multiple modes for research, coding, and creative tasks",
    website_url: "https://you.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 15,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2020,
    hq_country: "US",
    key_strengths: ["No personal data sold to advertisers", "Smart, Research, and Create modes in one interface", "Cite real web sources for every answer", "You API for enterprise search", "Code mode with live execution"],
    category_slug: "search-research",
    overview_general: "You.com is a privacy-focused AI search engine that combines traditional web results with AI-generated answers. It offers specialized modes: Smart for quick answers, Research for deep citations, and Create for writing. Unlike Google, You.com does not sell personal data.",
    overview_technical: "The You API provides an AI web search endpoint for RAG applications, returning AI-summarized answers with cited web sources. Supports structured JSON responses. Enterprise tier offers white-labeling and volume pricing. Model routing uses Claude, GPT-4, and proprietary retrieval models.",
  },
  {
    slug: "kagi",
    name: "Kagi",
    tagline: "Ad-free, privacy-preserving search engine with AI summaries and user-controlled result ranking",
    website_url: "https://kagi.com",
    logo_url: null,
    pricing_tier: "paid",
    has_free_tier: false,
    pricing_starts_at: 10,
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2018,
    hq_country: "US",
    key_strengths: ["Zero ads, zero tracking, subscription-funded", "Personalizable result ranking (boost/block domains)", "Universal Summarizer for any URL or PDF", "Lenses for specialized searches", "FastGPT instant AI answers"],
    category_slug: "search-research",
    overview_general: "Kagi is a paid search engine ($10/month) that is entirely ad-free and does not track or sell user data — funded by subscriptions. You can personalize results by boosting domains you trust and blocking those you don't. FastGPT provides instant AI answers; the Universal Summarizer can summarize any web page or PDF.",
    overview_technical: "Kagi aggregates results from multiple indices plus proprietary crawling. The Kagi API exposes web search and Universal Summarizer endpoints. FastGPT uses a mix of Claude and internal models with web augmentation. Lenses are filterable URL blocklists applied at query time.",
  },

  // ── Agent / automation ────────────────────────────────────────────────────
  {
    slug: "n8n",
    name: "n8n",
    tagline: "Open-source workflow automation platform with native AI agent nodes and 400+ integrations",
    website_url: "https://n8n.io",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 20,
    audience_fit: "technical",
    model_provider: null,
    open_source: true,
    self_hostable: true,
    api_available: true,
    founded_year: 2019,
    hq_country: "DE",
    key_strengths: ["Self-hostable (fair-code license)", "70+ native AI/LLM nodes with LangChain integration", "400+ app integrations", "Execution-based pricing instead of per-Zap", "Code nodes for custom JavaScript/Python logic"],
    category_slug: "agent-automation",
    overview_general: "n8n is an open-source workflow automation tool that you can self-host for free. Like Zapier but with far more developer flexibility, it connects 400+ apps and has native AI agent nodes for building LLM-powered automation. Popular with technical teams who want the power of Zapier without per-task pricing at scale.",
    overview_technical: "n8n 2.0 features 70+ AI nodes with first-class LangChain integration for multi-step agent workflows. Execution-based pricing on cloud tiers; self-hosted version is free and unlimited. Supports JavaScript/Python code nodes, custom webhooks, and credential management.",
  },
  {
    slug: "bardeen",
    name: "Bardeen",
    tagline: "AI browser automation agent that scrapes, enriches, and moves data without writing code",
    website_url: "https://bardeen.ai",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 10,
    audience_fit: "non_technical",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2020,
    hq_country: "US",
    key_strengths: ["Browser extension with no-code recorder", "AI Magic Box generates automations from plain English", "Scrapes any website without API keys", "Built-in integrations for CRM enrichment", "Runs in background with no server needed"],
    category_slug: "agent-automation",
    overview_general: "Bardeen is an AI automation tool that lives in your browser. The Magic Box feature lets you describe what you want and it builds the automation. Used by sales and marketing teams to automate manual data work without needing developers or API credentials.",
    overview_technical: "Bardeen's Chrome extension acts as a browser automation runtime that can interact with any webpage DOM. Automations are stored in the cloud and triggered manually, on schedule, or by webhook. The underlying AI uses LLMs to parse natural language descriptions into playbook steps.",
  },
  {
    slug: "agentgpt",
    name: "AgentGPT",
    tagline: "Web-based autonomous AI agent that chains GPT tasks together to complete multi-step goals",
    website_url: "https://agentgpt.reworkd.ai",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 20,
    audience_fit: "both",
    model_provider: "OpenAI",
    open_source: true,
    self_hostable: true,
    api_available: false,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["No-setup web interface for autonomous agents", "Open source and self-hostable", "Chains tool use across web search, code, and APIs", "Visual task tree for transparency", "Free tier with limited runs"],
    category_slug: "agent-automation",
    overview_general: "AgentGPT is a browser-based interface for running autonomous AI agents. You give it a goal, and it breaks it into tasks, executes each one with tools like web search and code execution, then compiles results. No technical setup required.",
    overview_technical: "Open source on GitHub (Reworkd); uses GPT-3.5/GPT-4 with ReAct-style agent prompting. Task execution loop calls tools including web search (SerpAPI) and code execution. Self-hostable with Docker; requires OpenAI API key. Front-end in Next.js, backend in FastAPI.",
  },
  {
    slug: "langchain",
    name: "LangChain",
    tagline: "Open-source Python/JS framework for building LLM-powered apps with chains, agents, and RAG",
    website_url: "https://langchain.com",
    logo_url: null,
    pricing_tier: "free",
    has_free_tier: true,
    pricing_starts_at: null,
    audience_fit: "technical",
    model_provider: null,
    open_source: true,
    self_hostable: true,
    api_available: false,
    founded_year: 2022,
    hq_country: "US",
    key_strengths: ["Most widely adopted LLM framework (~100K GitHub stars)", "Supports every major LLM and vector store", "LangGraph for complex stateful agent workflows", "LCEL for composable chains", "Integrations with 100+ tools and data sources"],
    category_slug: "agent-automation",
    overview_general: "LangChain is the most popular open-source framework for building applications with large language models. It provides abstractions for prompting, chaining LLM calls, connecting to tools, managing memory, and building RAG pipelines.",
    overview_technical: "Available in Python and TypeScript. LangGraph extends LangChain with a directed graph execution model for stateful, multi-actor agent workflows with persistence and streaming. Integrates with 100+ LLM providers, vector databases, and document loaders.",
  },
  {
    slug: "zapier",
    name: "Zapier",
    tagline: "No-code automation platform connecting 8,000+ apps with native AI agent capabilities",
    website_url: "https://zapier.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 19.99,
    audience_fit: "non_technical",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2011,
    hq_country: "US",
    key_strengths: ["8,000+ app integrations", "Zapier Agents for autonomous multi-step task execution", "No code required for most automations", "Instant trigger reliability", "Largest ecosystem of pre-built Zap templates"],
    category_slug: "agent-automation",
    overview_general: "Zapier is the leading no-code automation platform, connecting over 8,000 apps so non-technical users can automate repetitive workflows without writing code. Zapier Agents extends this with AI that can take autonomous actions across apps. The free plan gives 100 tasks/month.",
    overview_technical: "Zapier Zaps run as managed webhook-triggered serverless workflows. The Zapier Agent uses tool-use LLMs to decide which app actions to take based on a goal. REST API enables triggering Zaps programmatically.",
  },

  // ── Developer / infra tools ───────────────────────────────────────────────
  {
    slug: "hugging-face",
    name: "Hugging Face",
    tagline: "The GitHub of AI: 800K+ open models, datasets, and home of the Transformers library",
    website_url: "https://huggingface.co",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 9,
    audience_fit: "technical",
    model_provider: null,
    open_source: true,
    self_hostable: true,
    api_available: true,
    founded_year: 2016,
    hq_country: "US",
    key_strengths: ["800K+ open-source models and datasets", "Transformers, Diffusers, PEFT libraries", "Serverless Inference API with free tier", "Spaces for demos and Gradio apps", "Hub for sharing and discovering fine-tuned models"],
    category_slug: "developer-tools",
    overview_general: "Hugging Face is the central hub for open-source AI, hosting over 800,000 models, datasets, and demo Spaces. It's where researchers publish new models and where developers go to find pre-trained checkpoints for everything from text generation to image segmentation.",
    overview_technical: "The Hub exposes a Git-based model repository with LFS for weights. The Inference API provides serverless REST endpoints for 1,000s of models with free usage and pay-per-request beyond that. Inference Endpoints offers dedicated deployments. Libraries: Transformers, Diffusers, Datasets, PEFT, TRL are all Apache-licensed.",
  },
  {
    slug: "groq",
    name: "Groq",
    tagline: "LPU inference chips delivering 750 tokens/sec — the fastest publicly available LLM API",
    website_url: "https://groq.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: null,
    audience_fit: "technical",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2016,
    hq_country: "US",
    key_strengths: ["750 tokens/sec on Llama 70B — fastest available", "Sub-100ms time-to-first-token", "OpenAI-compatible API", "Free tier with rate limits, no credit card", "From $0.05/M tokens — among cheapest inference"],
    category_slug: "developer-tools",
    overview_general: "Groq built custom Language Processing Unit (LPU) chips for LLM inference — the result is the fastest publicly available API for running open models like Llama and Qwen. Developers use Groq when latency matters, like real-time voice apps or interactive coding agents.",
    overview_technical: "GroqCloud exposes an OpenAI-compatible REST API. Serves Llama 4, Llama 3.3, Qwen, Mistral, and DeepSeek models. Input pricing from $0.05/M tokens; output from $0.08/M. Supports streaming and function calling.",
  },
  {
    slug: "together-ai",
    name: "Together AI",
    tagline: "Cloud platform for running and fine-tuning open-source LLMs at scale with a unified API",
    website_url: "https://together.ai",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: null,
    audience_fit: "technical",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2022,
    hq_country: "US",
    key_strengths: ["200+ open-source models via single API", "$100 free credits at signup", "Serverless and dedicated GPU deployment", "Fine-tuning pipeline included", "OpenAI-compatible endpoints"],
    category_slug: "developer-tools",
    overview_general: "Together AI is a cloud inference platform for open-source LLMs. Developers get access to 200+ models — including Llama, Mistral, Qwen, and DeepSeek — through a single OpenAI-compatible API. $100 in free credits at signup covers substantial testing.",
    overview_technical: "Together's API is OpenAI-compatible with unified chat and completion endpoints. Serverless endpoints auto-scale per request; dedicated endpoints offer guaranteed throughput. Fine-tuning uses LoRA/QLoRA. Supports streaming, function calling, and JSON mode.",
  },
  {
    slug: "langsmith",
    name: "LangSmith",
    tagline: "LLM observability platform for tracing, evaluating, and debugging LangChain apps in production",
    website_url: "https://smith.langchain.com",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 39,
    audience_fit: "technical",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Full trace visualization for LangChain and LangGraph runs", "Human feedback and automated evaluation datasets", "Prompt playground and comparison", "Works with any LLM framework via SDK", "Free tier with 5K traces/month"],
    category_slug: "developer-tools",
    overview_general: "LangSmith is the observability and testing platform for LLM applications, built by the LangChain team. It captures every prompt, intermediate step, and output in your application as a trace, letting you debug failures and measure quality.",
    overview_technical: "Integrates with LangChain and LangGraph via automatic tracing (LANGCHAIN_TRACING_V2=true). The SDK wraps any LLM call for custom tracing. Evaluation datasets support human annotation and LLM-as-judge scoring. REST API for querying traces and triggering evaluation runs.",
  },
  {
    slug: "weights-and-biases",
    name: "Weights & Biases",
    tagline: "ML experiment tracking, model evaluation, and LLMOps platform used by leading AI teams",
    website_url: "https://wandb.ai",
    logo_url: null,
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 50,
    audience_fit: "technical",
    model_provider: null,
    open_source: false,
    self_hostable: true,
    api_available: true,
    founded_year: 2017,
    hq_country: "US",
    key_strengths: ["Industry standard for ML experiment tracking", "Weave module for LLM tracing and evaluation", "Sweeps for hyperparameter optimization", "Model registry with lineage tracking", "Acquired by CoreWeave — deep GPU cluster integration"],
    category_slug: "developer-tools",
    overview_general: "Weights & Biases (W&B) is the de facto standard for ML experiment tracking, used by AI teams at OpenAI, NVIDIA, and leading research labs. The free tier covers individual researchers; teams pay $50/seat. The Weave module extends W&B into LLM evaluation and tracing.",
    overview_technical: "The wandb Python library instruments training runs capturing metrics, system stats, checkpoints, and media. Sweeps runs Bayesian or grid hyperparameter searches. The W&B API enables programmatic access to run histories and artifacts. Acquired by CoreWeave in March 2025.",
  },
  {
    slug: "vercel-ai-sdk",
    name: "Vercel AI SDK",
    tagline: "TypeScript toolkit for building streaming AI chat apps with React and multiple LLM providers",
    website_url: "https://sdk.vercel.ai",
    logo_url: null,
    pricing_tier: "free",
    has_free_tier: true,
    pricing_starts_at: null,
    audience_fit: "technical",
    model_provider: null,
    open_source: true,
    self_hostable: true,
    api_available: false,
    founded_year: 2023,
    hq_country: "US",
    key_strengths: ["Single API for OpenAI, Anthropic, Google, Groq, and 20+ providers", "useChat and useCompletion React hooks", "Streaming with SSE out of the box", "Structured output (generateObject) with Zod schema", "Tool use and multi-step agent support"],
    category_slug: "developer-tools",
    overview_general: "The Vercel AI SDK is a free, open-source TypeScript library that makes it easy to build AI-powered web applications. It provides React hooks for streaming chat interfaces and a unified API that works with OpenAI, Anthropic, Google Gemini, Groq, and 20+ other providers.",
    overview_technical: "Provides useChat, useCompletion, and useObject React hooks with streaming via SSE. generateText, streamText, generateObject, and streamObject work in Edge Runtime, Node.js, and Bun. Provider adapters are first-class packages (@ai-sdk/openai, @ai-sdk/anthropic, etc.).",
  },
];

// ── main ────────────────────────────────────────────────────────────────────
async function main() {
  console.log(`\n🚀 Inserting ${TOOLS.length} AI tools…\n`);

  // Fetch all categories once
  const { data: categories, error: catErr } = await supabase
    .from("categories")
    .select("id, slug");

  if (catErr || !categories) {
    console.error("Failed to fetch categories:", catErr);
    process.exit(1);
  }

  const dbCatMap = Object.fromEntries(categories.map((c) => [c.slug, c.id]));

  let ok = 0;
  let skipped = 0;

  for (const t of TOOLS) {
    process.stdout.write(`  → ${t.name}... `);

    const dbCatSlug = CAT_MAP[t.category_slug];
    const catId = dbCatSlug ? dbCatMap[dbCatSlug] : null;

    if (!catId) {
      console.log(`⚠  unknown category "${t.category_slug}" → "${dbCatSlug}", skipping`);
      skipped++;
      continue;
    }

    const { data: tool, error: toolErr } = await supabase
      .from("tools")
      .upsert(
        {
          slug: t.slug,
          name: t.name,
          tagline: t.tagline,
          website_url: t.website_url,
          logo_url: t.logo_url ?? null,
          primary_category_id: catId,
          pricing_tier: t.pricing_tier as "free" | "freemium" | "paid" | "enterprise",
          has_free_tier: t.has_free_tier,
          pricing_starts_at: t.pricing_starts_at ?? null,
          audience_fit: t.audience_fit as "technical" | "non_technical" | "both",
          model_provider: t.model_provider ?? null,
          open_source: t.open_source,
          self_hostable: t.self_hostable,
          api_available: t.api_available,
          founded_year: t.founded_year ?? null,
          hq_country: t.hq_country ?? null,
          key_strengths: [...t.key_strengths],
          status: "published",
          published_at: new Date().toISOString(),
        },
        { onConflict: "slug", ignoreDuplicates: false },
      )
      .select("id")
      .single();

    if (toolErr || !tool) {
      console.log(`✗ ${toolErr?.message}`);
      skipped++;
      continue;
    }

    // Category junction
    await supabase.from("tool_categories").upsert(
      { tool_id: tool.id, category_id: catId },
      { onConflict: "tool_id,category_id", ignoreDuplicates: true },
    );

    // Content blocks — only overview (the researched data)
    await supabase.from("content_blocks").delete()
      .eq("tool_id", tool.id)
      .in("section", ["overview"]);

    await supabase.from("content_blocks").insert([
      {
        tool_id: tool.id,
        section: "overview",
        audience: "technical",
        body_md: t.overview_technical,
        sort_order: 0,
        heading: null,
      },
      {
        tool_id: tool.id,
        section: "overview",
        audience: "non_technical",
        body_md: t.overview_general,
        sort_order: 1,
        heading: null,
      },
    ]);

    console.log("✓");
    ok++;
  }

  console.log(`\n✅ Done — ${ok} inserted/updated, ${skipped} skipped\n`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
