/**
 * Seed script — populates 14 starter tools + content blocks.
 * Run via:  npm run db:seed
 * Requires: SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY in .env.local
 */
import { config } from "dotenv";
config({ path: ".env.local" });
config(); // also load .env as fallback
import { createClient } from "@supabase/supabase-js";
import type { Database } from "../app/types/database";

const supabase = createClient<Database>(
  process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL ?? "",
  process.env.SUPABASE_SERVICE_ROLE_KEY ?? ""
);

// ---------------------------------------------------------------------------
// Tool definitions
// ---------------------------------------------------------------------------
const TOOLS = [
  {
    slug: "chatgpt",
    name: "ChatGPT",
    tagline: "OpenAI's conversational AI — the world's most widely-used LLM interface.",
    website_url: "https://chat.openai.com",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 20,
    pricing_currency: "USD",
    audience_fit: "both",
    model_provider: "OpenAI",
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2022,
    hq_country: "US",
    hq_city: "San Francisco",
    key_strengths: ["conversational AI", "broad knowledge", "plugins/tools", "code generation"],
    category_slug: "chat-assistants",
    overview_technical: `ChatGPT is built on OpenAI's GPT-4o family of models. It supports multi-turn conversations, function calling via the Assistants API, file uploads, image generation (via DALL·E), and web browsing. The API is REST-based and offers streaming via SSE.\n\n\`\`\`bash\ncurl https://api.openai.com/v1/chat/completions \\\n  -H "Authorization: Bearer $OPENAI_KEY" \\\n  -d '{"model":"gpt-4o","messages":[{"role":"user","content":"Hello"}]}'\n\`\`\``,
    overview_general: `ChatGPT is an AI assistant you chat with in plain English. Ask it to help write emails, explain concepts, brainstorm ideas, or answer questions. The free tier is generous; ChatGPT Plus ($20/month) unlocks GPT-4o and the latest features.`,
    docs_technical: `## API Reference\n\nOpenAI exposes a REST API compatible with the official SDKs for Python, Node, Go, and others.\n\n### Chat Completions\n\n- Endpoint: \`POST /v1/chat/completions\`\n- Supports: streaming, function calling, structured outputs (JSON mode), vision (image inputs)\n- Rate limits: vary by tier — see platform.openai.com/account/limits\n\n### Assistants API\n\nStateful thread-based API with file search, code interpreter, and custom tool use.`,
    docs_general: `## Getting Started\n\n1. Visit [chat.openai.com](https://chat.openai.com) and create a free account.\n2. Type your question or request in the chat box.\n3. Upgrade to **ChatGPT Plus** ($20/month) for faster responses and access to GPT-4o.\n\n### Tips\n- Be specific: "Write a 3-bullet summary of this article for a non-technical audience" works better than "summarize."\n- Use **memory** (Settings → Personalization) to help ChatGPT remember your preferences.`,
    use_cases_technical: `- **Code review**: paste a function and ask for security or performance issues\n- **Unit test generation**: "Write Jest tests for this TypeScript function"\n- **Documentation**: "Turn these JSDoc comments into a README section"\n- **Regex / SQL**: describe the pattern in English, get the query back`,
    use_cases_general: `- **Email drafting**: "Write a polite follow-up email to a client who hasn't replied"\n- **Brainstorming**: "Give me 10 name ideas for a dog grooming business"\n- **Learning**: "Explain compound interest like I'm 12"\n- **Trip planning**: "Build a 5-day itinerary for Kyoto in April"`,
  },
  {
    slug: "claude",
    name: "Claude",
    tagline: "Anthropic's safety-focused AI assistant — exceptional at long documents and nuanced reasoning.",
    website_url: "https://claude.ai",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Claude_AI_logo.svg",
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 20,
    pricing_currency: "USD",
    audience_fit: "both",
    model_provider: "Anthropic",
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2021,
    hq_country: "US",
    hq_city: "San Francisco",
    key_strengths: ["200K context window", "coding", "long document analysis", "instruction following"],
    category_slug: "chat-assistants",
    overview_technical: `Claude is built on Anthropic's Claude 3.x/4.x model family. Key technical differentiators: 200K token context window, Constitutional AI training for safety, and structured output via tool_use. The API is REST-based and fully streaming-capable.\n\n\`\`\`python\nimport anthropic\nclient = anthropic.Anthropic()\nmsg = client.messages.create(\n    model="claude-opus-4-5",\n    max_tokens=1024,\n    messages=[{"role": "user", "content": "Explain RLHF."}]\n)\nprint(msg.content[0].text)\n\`\`\``,
    overview_general: `Claude is an AI assistant made by Anthropic. It's known for being careful, honest, and good at working with long documents like PDFs or research papers. The free tier is solid; Claude Pro ($20/month) unlocks the most powerful models and priority access.`,
    docs_technical: `## API Overview\n\n- Endpoint: \`POST https://api.anthropic.com/v1/messages\`\n- Auth: \`x-api-key\` header\n- Models: claude-opus-4-5, claude-sonnet-4-5, claude-haiku-3-5\n- Features: streaming, tool use (function calling), vision, PDF reading\n\n### Context caching\n\nPrompt caching reduces cost by up to 90% for repeated prefixes. Pass \`cache_control: { type: "ephemeral" }\` on the content block to cache.`,
    docs_general: `## Getting Started\n\n1. Go to [claude.ai](https://claude.ai) and sign in with Google or email.\n2. Start a new conversation — paste in a long document or just ask a question.\n3. **Pro tip**: upload a PDF and ask Claude to summarize the key findings.\n\n### What Claude is great at\n- Summarising long research papers or legal documents\n- Writing with a consistent voice and tone\n- Giving thoughtful, nuanced answers on complex topics`,
    use_cases_technical: `- **Large codebase Q&A**: paste an entire repo context and ask architectural questions\n- **Structured extraction**: use tool_use to extract JSON from unstructured text reliably\n- **Diff review**: paste a large diff and ask Claude to identify logic bugs\n- **Migration planning**: "Migrate this Express.js code to Hono + TypeScript"`,
    use_cases_general: `- **Research assistant**: upload academic papers and ask for plain-English summaries\n- **Writing coach**: paste a draft and ask "make this sound more confident"\n- **Meeting prep**: paste a briefing doc, ask "what are the 3 things I need to know?"\n- **Book club**: "What's the main argument of this chapter?"`,
  },
  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    tagline: "AI pair programmer that autocompletes and generates code inside your editor.",
    website_url: "https://github.com/features/copilot",
    logo_url: "https://github.githubassets.com/images/modules/site/copilot/copilot.png",
    pricing_tier: "paid",
    has_free_tier: true,
    pricing_starts_at: 10,
    pricing_currency: "USD",
    audience_fit: "technical",
    model_provider: "OpenAI / Anthropic / Google",
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2021,
    hq_country: "US",
    hq_city: "San Francisco",
    key_strengths: ["inline autocomplete", "VS Code integration", "multi-model", "enterprise SSO"],
    category_slug: "coding",
    overview_technical: `GitHub Copilot integrates directly into VS Code, JetBrains IDEs, Neovim, and more. It uses a combination of OpenAI Codex, GPT-4o, Claude Sonnet, and Gemini depending on the context. Copilot Chat provides an inline chat interface with codebase awareness via embeddings.`,
    overview_general: `GitHub Copilot is an AI that helps you write code. As you type, it suggests the next line — or even the next function. Think of it as autocomplete on steroids. It works inside VS Code, PyCharm, and most popular editors.`,
    docs_technical: `## Setup\n\n1. Install the **GitHub Copilot** extension in VS Code.\n2. Sign in with your GitHub account (requires Copilot subscription).\n3. Start typing — gray ghost text will appear with suggestions; press \`Tab\` to accept.\n\n## Copilot Chat\n\nUse \`Ctrl+I\` (inline) or the sidebar chat panel. Key slash commands:\n- \`/explain\` — explain selected code\n- \`/fix\` — suggest fixes for errors\n- \`/tests\` — generate unit tests\n- \`/doc\` — add JSDoc / docstring`,
    docs_general: `## Getting Started\n\n1. Make sure you have a GitHub account.\n2. Subscribe to Copilot at github.com/features/copilot.\n3. Install the extension in your editor.\n4. Open any file and start typing — Copilot will suggest code in gray text. Press **Tab** to accept.`,
    use_cases_technical: `- **Boilerplate generation**: describe a function in a comment, Copilot writes the body\n- **Test generation**: \`/tests\` on any function produces a test suite\n- **Refactoring**: highlight code, ask Copilot Chat to "extract this into a hook"\n- **SQL queries**: describe the query in English in a comment, get the SQL back`,
    use_cases_general: `- **Learning by example**: Copilot shows you how experienced developers typically write something\n- **Reducing typos**: catches syntax errors before you even run the code\n- **Faster prototyping**: rough out an entire feature in a fraction of the time`,
  },
  {
    slug: "cursor",
    name: "Cursor",
    tagline: "AI-first code editor built on VS Code — full codebase context, not just the open file.",
    website_url: "https://cursor.sh",
    logo_url: "https://cursor.sh/brand/icon.svg",
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 20,
    pricing_currency: "USD",
    audience_fit: "technical",
    model_provider: "Anthropic / OpenAI",
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2022,
    hq_country: "US",
    hq_city: "San Francisco",
    key_strengths: ["codebase-wide context", "Composer multi-file edits", "Ctrl+K inline AI", "@mentions for files"],
    category_slug: "coding",
    overview_technical: `Cursor is a fork of VS Code that deeply integrates AI. It indexes your entire codebase into a vector store (local or remote) to provide accurate, context-aware completions. Key features: Composer (multi-file agentic edits), \`Ctrl+K\` (inline code generation), and \`Ctrl+L\` (chat with codebase context). Supports Claude Sonnet, GPT-4o, and Cursor's own model.`,
    overview_general: `Cursor is a code editor (like VS Code) with built-in AI. Unlike tools that only see the file you're working on, Cursor understands your whole project. You can describe a feature in plain English and it will write code across multiple files at once.`,
    docs_technical: `## Key Shortcuts\n\n| Shortcut | Action |\n|---|---|\n| \`Ctrl+K\` | Inline code generation / edit |\n| \`Ctrl+L\` | Open chat panel with codebase context |\n| \`Ctrl+I\` | Open Composer (multi-file agent) |\n| \`@filename\` | Pin a file to the context window |\n| \`@codebase\` | Search entire indexed codebase |\n\n## Composer\n\nComposer is Cursor's agentic mode. Describe a feature and it will create, edit, and delete files to implement it. Review the diff before accepting.`,
    docs_general: `## Getting Started\n\n1. Download Cursor at [cursor.sh](https://cursor.sh).\n2. Import your VS Code settings (one click).\n3. Open a project — Cursor will index it in the background.\n4. Press **Ctrl+L** and ask "How does the auth flow work in this codebase?"\n\nCursor Free gives you 2,000 completions/month. Pro ($20/month) unlocks unlimited requests.`,
    use_cases_technical: `- **Feature from scratch**: open Composer, describe the feature, review the multi-file diff\n- **Codebase onboarding**: ask "explain the data model" or "how does payment processing work?"\n- **Debugging**: paste the stack trace into chat, ask for the fix with \`@file\` context\n- **Refactoring**: "migrate all class components in src/components to functional components"`,
    use_cases_general: `- **Writing your first app**: describe what you want to build, Cursor generates the starting code\n- **Fixing bugs**: paste the error message, ask what's wrong\n- **Understanding someone else's code**: ask "what does this function do?"`,
  },
  {
    slug: "midjourney",
    name: "Midjourney",
    tagline: "Photorealistic and artistic image generation via a Discord-based interface.",
    website_url: "https://midjourney.com",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Midjourney_Emblem.png",
    pricing_tier: "paid",
    has_free_tier: false,
    pricing_starts_at: 10,
    pricing_currency: "USD",
    audience_fit: "both",
    model_provider: "Midjourney",
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2022,
    hq_country: "US",
    hq_city: "San Francisco",
    key_strengths: ["photorealism", "artistic styles", "consistent aesthetics", "v6 quality"],
    category_slug: "image-generation",
    overview_technical: `Midjourney v6 offers state-of-the-art image quality with photorealistic outputs and nuanced prompt adherence. The primary interface is Discord (/imagine command) with a web interface in beta. No public API — generation is only available through their interface. Supports reference images (--cref), style references (--sref), and multi-prompt weighting.`,
    overview_general: `Midjourney creates stunning images from text descriptions. Type what you want to see — a mountain landscape at sunset, a cyberpunk cat, a product photo — and Midjourney generates four image options. It's accessed through Discord (a chat app) or the website.`,
    docs_technical: `## Prompt Syntax\n\n\`\`\`\n/imagine prompt: [description] [--parameters]\n\`\`\`\n\n| Parameter | Effect |\n|---|---|\n| \`--ar 16:9\` | Aspect ratio |\n| \`--v 6\` | Model version |\n| \`--style raw\` | Less stylization |\n| \`--q 2\` | Higher quality (slower) |\n| \`--cref URL\` | Character reference image |\n| \`--sref URL\` | Style reference image |\n\n## Multi-prompt\n\nUse \`::\` to separate concepts with individual weights:\n\`sunset :: mountains ::2 snow :: -1 people\``,
    docs_general: `## Getting Started\n\n1. Join the [Midjourney Discord](https://discord.gg/midjourney) or visit [midjourney.com](https://midjourney.com).\n2. Subscribe ($10/month Basic for 200 images).\n3. In any #newbies channel, type \`/imagine prompt: a golden retriever wearing sunglasses\`.\n4. Pick your favorite from the 4 results and click **U1–U4** to upscale it.`,
    use_cases_technical: `- **Product mockups**: generate multiple visual concepts quickly before investing in photography\n- **Concept art**: early-stage ideation for games, films, or brand directions\n- **Style transfer**: use --sref to apply a consistent visual style across a series\n- **Architecture visualization**: render building concepts from descriptions`,
    use_cases_general: `- **Social media content**: create unique images for posts without stock photos\n- **Book covers / thumbnails**: quick illustration for blogs or presentations\n- **Gift personalization**: generate a portrait in a fantasy style for a friend\n- **Interior design inspiration**: "Scandinavian living room with warm lighting"`,
  },
  {
    slug: "runway",
    name: "Runway",
    tagline: "AI video generation and editing — Gen-3 produces cinematic clips from text or image.",
    website_url: "https://runwayml.com",
    logo_url: "https://assets-global.website-files.com/6257adef93867e50d84d30e2/658ddb8bd6f32dea82d77e59_Runway_Logo.png",
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 12,
    pricing_currency: "USD",
    audience_fit: "both",
    model_provider: "Runway",
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2018,
    hq_country: "US",
    hq_city: "New York",
    key_strengths: ["text-to-video", "image-to-video", "inpainting", "motion brush"],
    category_slug: "video",
    overview_technical: `Runway Gen-3 Alpha is a state-of-the-art video generation model supporting text-to-video (up to 10s), image-to-video, and video-to-video. The API (beta) accepts prompts and returns video URLs. Motion Brush allows frame-level motion control. Background removal and green screen tools are production-quality.`,
    overview_general: `Runway turns text prompts or images into short video clips. Describe a scene — "a golden retriever running on a beach at sunset, slow motion" — and Runway generates a realistic 5–10 second video. It's used by filmmakers, social media creators, and marketers.`,
    docs_technical: `## API (Beta)\n\n\`\`\`bash\ncurl -X POST https://api.runwayml.com/v1/image_to_video \\\n  -H "Authorization: Bearer $RUNWAY_KEY" \\\n  -d '{"promptImage":"https://...","promptText":"camera slowly zooms in","duration":5}'\n\`\`\`\n\nPolls for completion via GET on the returned task ID. Output is an mp4 URL valid for 24h.`,
    docs_general: `## Getting Started\n\n1. Sign up at [runwayml.com](https://runwayml.com) — free tier gives 125 credits.\n2. Click **New Project → Gen-3 Alpha**.\n3. Type a description or upload an image to animate.\n4. Click **Generate** and wait ~30 seconds.\n\nCredits are consumed per second of video generated.`,
    use_cases_technical: `- **Automated video pipelines**: use the API to generate B-roll for video production workflows\n- **Concept visualization**: rapid prototyping of visual effects concepts\n- **Dataset generation**: synthetic video data for training computer vision models\n- **Product demos**: animate 3D renders or mockup screenshots`,
    use_cases_general: `- **Social media clips**: animated intros or transitions for Instagram Reels / TikTok\n- **Ad creative**: quickly test multiple visual concepts before full production\n- **Storytelling**: bring illustrations or photos to life\n- **Presentations**: add dynamic visuals to pitch decks`,
  },
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    tagline: "Ultra-realistic text-to-speech and voice cloning with 1000+ voices in 29 languages.",
    website_url: "https://elevenlabs.io",
    logo_url: "https://elevenlabs.io/favicons/apple-touch-icon.png",
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 5,
    pricing_currency: "USD",
    audience_fit: "both",
    model_provider: "ElevenLabs",
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2022,
    hq_country: "US",
    hq_city: "New York",
    key_strengths: ["voice cloning", "29 languages", "streaming TTS", "Projects (long-form audio)"],
    category_slug: "audio-music",
    overview_technical: `ElevenLabs provides REST APIs for TTS (streaming and non-streaming), voice cloning (from ~1 min of audio), speech-to-speech conversion, and audio isolation. The Turbo v2.5 model offers ~300ms latency with streaming. WebSockets are supported for real-time TTS in conversational applications.`,
    overview_general: `ElevenLabs creates ultra-realistic voiceovers from text. Choose from 1,000+ voices or clone your own voice with a short recording. It supports 29 languages and can narrate audiobooks, podcasts, or YouTube videos with no recording needed.`,
    docs_technical: `## Streaming TTS\n\n\`\`\`python\nfrom elevenlabs.client import ElevenLabs\nfrom elevenlabs import stream\n\nclient = ElevenLabs(api_key="...")\naudio = client.generate(\n    text="Hello world",\n    voice="Rachel",\n    model="eleven_turbo_v2_5",\n    stream=True\n)\nstream(audio)\n\`\`\`\n\n## WebSocket (real-time)\n\nConnect to \`wss://api.elevenlabs.io/v1/text-to-speech/{voice_id}/stream-input\` for <300ms latency suitable for conversational AI.`,
    docs_general: `## Getting Started\n\n1. Sign up at [elevenlabs.io](https://elevenlabs.io) — free tier gives 10,000 characters/month.\n2. Click **Text to Speech** in the sidebar.\n3. Type or paste your text, choose a voice, click **Generate**.\n4. Download the MP3 or copy the URL.\n\nFor audiobooks, use **Projects** to narrate chapters with consistent voice and pacing.`,
    use_cases_technical: `- **Conversational AI voice**: real-time TTS for chatbot or voice assistant responses\n- **Podcast automation**: generate audio from a written script with custom branded voice\n- **Voice cloning pipeline**: clone a spokesperson's voice for localized content at scale\n- **Accessibility**: convert long-form articles to audio for screen-reader alternatives`,
    use_cases_general: `- **YouTube narration**: record a voiceover for your video without a microphone\n- **Audiobook creation**: turn your written book into an audiobook in hours\n- **Language learning**: listen to text in a native accent to improve pronunciation\n- **Corporate training**: generate professional training narration from scripts`,
  },
  {
    slug: "perplexity",
    name: "Perplexity AI",
    tagline: "AI-powered search engine that answers questions with cited, up-to-date sources.",
    website_url: "https://perplexity.ai",
    logo_url: "https://www.perplexity.ai/favicon.svg",
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 20,
    pricing_currency: "USD",
    audience_fit: "both",
    model_provider: "Perplexity / OpenAI / Anthropic",
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2022,
    hq_country: "US",
    hq_city: "San Francisco",
    key_strengths: ["real-time web search", "cited sources", "Sonar API", "follow-up questions"],
    category_slug: "search-research",
    overview_technical: `Perplexity's Sonar API wraps their search-augmented LLM as an OpenAI-compatible endpoint. Models: \`sonar-small-online\`, \`sonar-large-online\`, \`sonar-huge-online\`. Each response includes \`citations\` array with source URLs and snippets. Ideal for RAG pipelines needing real-time grounded answers.`,
    overview_general: `Perplexity is like a search engine that actually answers your question instead of just listing links. Type "What's the latest on the Mars missions?" and Perplexity pulls from current web sources and writes a clear answer with links to every fact.`,
    docs_technical: `## Sonar API\n\n\`\`\`python\nfrom openai import OpenAI\nclient = OpenAI(api_key="pplx-...", base_url="https://api.perplexity.ai")\nresp = client.chat.completions.create(\n    model="sonar-large-online",\n    messages=[{"role": "user", "content": "Latest AI research in 2025?"}]\n)\nprint(resp.choices[0].message.content)\n# resp.citations — list of source URLs\n\`\`\``,
    docs_general: `## Getting Started\n\n1. Visit [perplexity.ai](https://perplexity.ai) — no account needed to start searching.\n2. Type your question naturally, like you'd ask a person.\n3. Read the answer and check the sources on the right panel.\n4. Ask **follow-up questions** in the same thread — Perplexity remembers the context.\n\nPro ($20/month) unlocks GPT-4o and Claude responses, unlimited file uploads.`,
    use_cases_technical: `- **Grounded RAG**: use Sonar as the retrieval step instead of building your own web scraper\n- **Competitive intelligence**: automated daily summaries of competitor news\n- **Research pipelines**: chain Sonar queries to gather data for analysis agents\n- **Fact-checking**: verify claims with citation-backed responses`,
    use_cases_general: `- **Current events**: "What happened with [topic] this week?" with real sources\n- **Product research**: compare products with up-to-date pricing and reviews\n- **Academic research**: get a literature overview with links to actual papers\n- **Travel planning**: ask about visa requirements or entry rules with current info`,
  },
  {
    slug: "grammarly",
    name: "Grammarly",
    tagline: "AI writing assistant that catches grammar errors and improves clarity in real time.",
    website_url: "https://grammarly.com",
    logo_url: "https://static.grammarly.com/assets/files/efe57d016b8be8d7b2f4c1e8b5461a06/grammarly_logo.svg",
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 12,
    pricing_currency: "USD",
    audience_fit: "non_technical",
    model_provider: "Grammarly",
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2009,
    hq_country: "US",
    hq_city: "San Francisco",
    key_strengths: ["grammar + spelling", "tone detection", "plagiarism check", "browser extension"],
    category_slug: "writing",
    overview_technical: `Grammarly offers a browser extension, desktop app, and API (enterprise). The real-time suggestions run a custom NLP pipeline trained on billions of sentences. The API (Grammarly Text Editor SDK) allows embedding Grammarly suggestions into any web textarea. GrammarlyGO (generative AI) uses an LLM for rewriting and tone adjustment.`,
    overview_general: `Grammarly is an AI writing helper that works everywhere you type — Gmail, Google Docs, Slack, LinkedIn. It underlines mistakes and suggests fixes as you write. Free catches grammar and spelling; Premium improves clarity, tone, and style.`,
    docs_technical: `## Text Editor SDK\n\nEmbed Grammarly into your app's textarea:\n\n\`\`\`js\nimport { init } from "@grammarly/editor-sdk";\nconst Grammarly = await init("CLIENT_ID");\nGrammarly.withText(document.querySelector("#editor"));\n\`\`\`\n\nRequires a Grammarly for Developers account. The SDK adds real-time underlines and a suggestions panel without leaving your app.`,
    docs_general: `## Getting Started\n\n1. Install the **Grammarly browser extension** for Chrome/Firefox.\n2. Sign in (free account works).\n3. Visit Gmail, Google Docs, or any website with a text box.\n4. Start typing — Grammarly will underline issues in red, yellow, and blue.\n5. Click any underline to see the suggestion and accept it.\n\nGrammarly Premium adds style, clarity, and tone suggestions.`,
    use_cases_technical: `- **Embed in SaaS apps**: use the SDK to add writing quality checks to your CMS or email tool\n- **Automated proofreading**: use the API to batch-check content before publishing\n- **Enterprise compliance**: enforce writing standards across communications with custom style guides`,
    use_cases_general: `- **Email writing**: catch typos before sending an important message\n- **Cover letters / resumes**: ensure professional tone and zero grammar errors\n- **Social media**: improve clarity of posts before publishing\n- **Non-native speakers**: get real-time corrections while learning English writing conventions`,
  },
  {
    slug: "notion-ai",
    name: "Notion AI",
    tagline: "AI writing and thinking assistant built directly into Notion's docs and databases.",
    website_url: "https://notion.so/product/ai",
    logo_url: "https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png",
    pricing_tier: "freemium",
    has_free_tier: false,
    pricing_starts_at: 10,
    pricing_currency: "USD",
    audience_fit: "both",
    model_provider: "Anthropic / OpenAI",
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2016,
    hq_country: "US",
    hq_city: "San Francisco",
    key_strengths: ["in-page AI editing", "Q&A over workspace", "auto-fill databases", "summaries"],
    category_slug: "presentations-docs",
    overview_technical: `Notion AI is deeply integrated into Notion's block-based editor. It uses Claude and GPT-4o under the hood. Key capabilities: /AI commands inline (summarize, translate, fix spelling), Q&A over entire workspace via embeddings, and database auto-fill (generate column values using AI from adjacent data). No standalone API.`,
    overview_general: `Notion AI is an add-on ($10/month per member) that brings AI directly into your Notion workspace. Highlight text and ask it to rewrite, summarize, or translate. Ask questions like "What did we decide about the product roadmap?" and it searches your entire workspace.`,
    docs_technical: `## Key AI Features\n\n- **Inline AI**: type \`/AI\` or Space on an empty block to open the AI action menu\n- **AI Q&A**: open the sidebar, click AI tab, ask anything — searches your workspace\n- **Database auto-fill**: add an AI property to a database, define a prompt using column values\n- **Summaries**: highlight any selection, click AI → Summarize\n\nNotion AI uses workspace embeddings that update in real-time as pages change.`,
    docs_general: `## Getting Started\n\n1. In any Notion page, press **Space** on an empty line to open the AI menu.\n2. Pick an action: **Write**, **Summarize**, **Fix grammar**, **Translate**, etc.\n3. For Q&A: click the AI button in the sidebar and ask your question.\n\nNotion AI costs $10/month per workspace member (add-on to any Notion plan).`,
    use_cases_technical: `- **Database enrichment**: auto-generate summaries, tags, or scores for each row using AI properties\n- **Documentation maintenance**: summarize long technical docs for the team wiki\n- **Meeting notes**: paste raw transcript, AI extracts action items and decisions\n- **CRM automation**: auto-fill lead status or next steps from call notes`,
    use_cases_general: `- **Meeting notes**: paste a messy transcript, get clean action items\n- **Blog drafting**: start with an outline, ask AI to expand each section\n- **Project planning**: "Turn this brainstorm into a structured project plan"\n- **Language translation**: translate your docs into another language instantly`,
  },
  {
    slug: "v0",
    name: "v0 by Vercel",
    tagline: "Generate production-ready UI components from text prompts using shadcn and Tailwind.",
    website_url: "https://v0.dev",
    logo_url: "https://v0.dev/favicon.ico",
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 20,
    pricing_currency: "USD",
    audience_fit: "technical",
    model_provider: "Anthropic / OpenAI",
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2023,
    hq_country: "US",
    hq_city: "San Francisco",
    key_strengths: ["shadcn/ui output", "live preview", "one-click deploy", "React + Tailwind"],
    category_slug: "design",
    overview_technical: `v0 generates React components using shadcn/ui primitives and Tailwind CSS. Outputs are copy-paste ready and production-quality. The v0 API (beta) accepts text/image prompts and returns JSX. Supports iterative refinement via chat. Components can be deployed to Vercel with one click or downloaded to integrate into any project.`,
    overview_general: `v0 is a tool by Vercel that generates working website components from a text description. Describe what you want — "a pricing table with three tiers" — and v0 writes the code and shows you a live preview. Non-developers can build UI prototypes; developers get clean, copy-paste code.`,
    docs_technical: `## API (Beta)\n\n\`\`\`bash\ncurl -X POST https://api.v0.dev/chat \\\n  -H "Authorization: Bearer $V0_API_KEY" \\\n  -d '{"messages":[{"role":"user","content":"Create a dark mode dashboard card"}]}'\n\`\`\`\n\nReturns streaming MDX with embedded React code blocks. Each code block is a standalone component using shadcn/ui + Tailwind.`,
    docs_general: `## Getting Started\n\n1. Go to [v0.dev](https://v0.dev) and sign in with your Vercel account.\n2. Type what you want to build: "a login form with email and password fields"\n3. Click a variant you like.\n4. Click **Copy** to copy the React code, or **Open in Vercel** to deploy immediately.\n\nFree tier gives 200 credits/month. Premium ($20/month) for unlimited.`,
    use_cases_technical: `- **Rapid UI prototyping**: generate a component, copy into your codebase, customize styles\n- **Design-to-code**: describe a Figma layout in words and get the JSX\n- **shadcn learning**: see how shadcn components compose for complex layouts\n- **Landing page sections**: hero, pricing, feature grids — generate and assemble`,
    use_cases_general: `- **No-code UI building**: design website sections without writing code\n- **Prototype for clients**: quickly show clients what a page could look like\n- **Learn web design**: see real code behind beautiful components\n- **Startup MVPs**: build a full landing page in under an hour`,
  },
  {
    slug: "make",
    name: "Make",
    tagline: "Visual no-code automation platform — connect apps and automate workflows with a drag-and-drop builder.",
    website_url: "https://make.com",
    logo_url: "https://www.make.com/en/help/image/uuid-8b74d1d7-c91e-37d0-05d9-4dcb8cff2f0d.png",
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 9,
    pricing_currency: "USD",
    audience_fit: "both",
    model_provider: null,
    open_source: false,
    self_hostable: false,
    api_available: true,
    founded_year: 2012,
    hq_country: "CZ",
    hq_city: "Prague",
    key_strengths: ["visual builder", "1500+ integrations", "AI module", "webhooks"],
    category_slug: "automation",
    overview_technical: `Make (formerly Integromat) is a visual integration platform with a scenario-based execution model. Modules map to API endpoints; the visual builder creates a directed graph of data transformations. The Make API allows creating/running scenarios programmatically. Supports custom HTTP modules for any REST API, webhooks, iterators, routers, and built-in AI modules (OpenAI, Claude, Anthropic).`,
    overview_general: `Make lets you automate repetitive tasks between apps without code. Connect Gmail to Notion to Slack, for example: "When I receive an email with 'invoice' in the subject, extract the amount, add it to my Notion database, and notify me on Slack." Over 1,500 apps supported.`,
    docs_technical: `## Make API\n\nCreate and trigger scenarios via API:\n\n\`\`\`bash\n# Run a scenario\ncurl -X POST "https://eu1.make.com/api/v2/scenarios/{scenarioId}/run" \\\n  -H "Authorization: Token $MAKE_API_KEY"\n\`\`\`\n\n## Custom Modules\n\nFor any REST API not natively supported, use the HTTP module. Define:\n- URL (with dynamic variables from previous modules)\n- Auth headers\n- Request/response mapping\n\nThe JSONata expression language handles complex data transformations.`,
    docs_general: `## Getting Started\n\n1. Sign up at [make.com](https://make.com) — free tier gives 1,000 operations/month.\n2. Click **Create a new scenario**.\n3. Click the **+** to add a first module (trigger) — e.g., Gmail: Watch Emails.\n4. Add more modules to transform and route data.\n5. Click **Run once** to test, then schedule it.\n\nEach action in a scenario (sending an email, creating a row) counts as one operation.`,
    use_cases_technical: `- **API orchestration**: chain REST API calls with data transformation between steps\n- **Event-driven pipelines**: webhook trigger → process → push to database\n- **AI workflows**: receive form submission → call Claude API → post result to Slack\n- **Data sync**: keep records in sync between CRM, database, and spreadsheets`,
    use_cases_general: `- **Lead capture**: form submission → add to CRM → send welcome email → notify sales team\n- **Social media**: schedule posts across platforms from a single spreadsheet\n- **Invoicing**: auto-generate and send invoices when a project is marked complete\n- **Reporting**: generate weekly reports from multiple data sources automatically`,
  },
  {
    slug: "replicate",
    name: "Replicate",
    tagline: "Run open-source AI models in the cloud via a simple API — images, video, audio, and LLMs.",
    website_url: "https://replicate.com",
    logo_url: "https://replicate.com/static/favicon.png",
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: null,
    pricing_currency: "USD",
    audience_fit: "technical",
    model_provider: "Various (open-source)",
    open_source: true,
    self_hostable: false,
    api_available: true,
    founded_year: 2021,
    hq_country: "US",
    hq_city: "San Francisco",
    key_strengths: ["1000s of open-source models", "pay-per-second", "Cog packaging", "deployments"],
    category_slug: "infrastructure",
    overview_technical: `Replicate provides a cloud API for running open-source ML models (Stable Diffusion, Llama, Whisper, SDXL, Flux, etc.). Models are packaged with Cog (their Docker-based ML container tool). The REST API accepts model input and returns output via polling or webhooks. Usage is billed per second of GPU compute. Replicate Deployments allow dedicated, always-on model instances.`,
    overview_general: `Replicate is a cloud platform where you can run thousands of open-source AI models with one API call. Need to generate an image with Stable Diffusion, transcribe audio with Whisper, or run Llama? Replicate handles the GPU infrastructure so you don't have to.`,
    docs_technical: `## Running a prediction\n\n\`\`\`python\nimport replicate\noutput = replicate.run(\n    "black-forest-labs/flux-schnell",\n    input={"prompt": "a photorealistic cat astronaut", "num_outputs": 4}\n)\nfor url in output:\n    print(url)  # direct image URLs\n\`\`\`\n\n## Webhooks\n\nPass \`webhook\` + \`webhook_events_filter\` to receive async notifications instead of polling. Useful for long-running models.`,
    docs_general: `## Getting Started\n\n1. Sign up at [replicate.com](https://replicate.com).\n2. Browse models at replicate.com/explore.\n3. Each model page has a live demo and auto-generated API code.\n4. Get your API key and start calling models from your app.\n\nYou pay only for GPU time used — fractions of a cent per image, a few cents per minute of video.`,
    use_cases_technical: `- **Multi-model pipelines**: run Whisper for transcription → LLM for summarization → TTS for audio\n- **Fine-tuned models**: train and host custom models (SDXL fine-tunes, LoRAs)\n- **Batch processing**: run thousands of predictions in parallel via the predictions API\n- **Model comparison**: same prompt across multiple models for A/B evaluation`,
    use_cases_general: `- **Image generation**: access Stable Diffusion and Flux without local GPU setup\n- **Audio transcription**: transcribe long recordings with Whisper for a few cents\n- **Background removal**: rembg model removes backgrounds from product photos\n- **Upscaling**: Real-ESRGAN upscales old photos to 4K quality`,
  },
  {
    slug: "suno",
    name: "Suno",
    tagline: "AI music generation — create full songs with vocals, instruments, and lyrics from a text prompt.",
    website_url: "https://suno.com",
    logo_url: "https://suno.com/favicon.ico",
    pricing_tier: "freemium",
    has_free_tier: true,
    pricing_starts_at: 8,
    pricing_currency: "USD",
    audience_fit: "both",
    model_provider: "Suno",
    open_source: false,
    self_hostable: false,
    api_available: false,
    founded_year: 2023,
    hq_country: "US",
    hq_city: "Cambridge",
    key_strengths: ["full song generation", "vocals included", "genre control", "custom lyrics"],
    category_slug: "audio-music",
    overview_technical: `Suno v4 generates full multi-track songs (up to ~4 minutes) including vocals, instruments, and mixing from text prompts. Custom mode allows providing lyrics directly. The model understands genre, mood, tempo, and instrumentation prompts. No public API yet — generation is only via the web interface or mobile app. Songs are generated at ~128kbps MP3.`,
    overview_general: `Suno creates full songs from a text description. Type "upbeat country song about a golden retriever who loves pizza" and Suno writes the lyrics, records the vocals, and produces all the instruments — in about 30 seconds. The free tier gives 50 credits per day.`,
    docs_technical: `## Prompt Engineering\n\nSuno responds well to genre + mood + instrumentation prompts:\n\n\`\`\`\n[Genre]: indie pop\n[Mood]: nostalgic, bittersweet\n[Instruments]: acoustic guitar, piano, light drums\n[About]: a programmer who ships code at 3am\n\`\`\`\n\nCustom mode: write your own lyrics with structural tags: [Verse], [Chorus], [Bridge], [Outro]. The model follows song structure instructions closely.`,
    docs_general: `## Getting Started\n\n1. Go to [suno.com](https://suno.com) and create an account.\n2. Click **Create** and type a song description.\n3. Hit **Create** — Suno generates 2 versions in ~30 seconds.\n4. Pick the one you like, download it, or share the link.\n\nFree tier: 50 credits/day (10 songs). Pro ($8/month) for 2,500 credits.`,
    use_cases_technical: `- **Background music for videos**: generate royalty-free music in any style to avoid licensing\n- **Jingle creation**: generate multiple variations quickly for client review\n- **Content creation automation**: batch-generate thematic music for a playlist or channel\n- **Prototype soundtracks**: test how different moods affect a video before hiring composers`,
    use_cases_general: `- **Personalized gifts**: create a song for someone's birthday with their name and story\n- **Meditation music**: "calm ambient music with rain sounds and gentle piano"\n- **Workout playlist**: generate high-energy tracks in your preferred genre\n- **Storytelling**: compose background music for a podcast episode or video`,
  },
] as const;

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main() {
  console.log("🌱 Seeding 14 starter tools...\n");

  // 1. Fetch all categories
  const { data: categories, error: catErr } = await supabase
    .from("categories")
    .select("id, slug");

  if (catErr || !categories) {
    console.error("Failed to fetch categories:", catErr);
    process.exit(1);
  }

  const catMap = Object.fromEntries(categories.map((c) => [c.slug, c.id]));

  for (const t of TOOLS) {
    process.stdout.write(`  → ${t.name}... `);

    // Upsert the tool (skip if slug already exists)
    const { data: tool, error: toolErr } = await supabase
      .from("tools")
      .upsert(
        {
          slug: t.slug,
          name: t.name,
          tagline: t.tagline,
          website_url: t.website_url,
          logo_url: t.logo_url,
          primary_category_id: catMap[t.category_slug] ?? null,
          pricing_tier: t.pricing_tier as "free" | "freemium" | "paid" | "enterprise",
          has_free_tier: t.has_free_tier,
          pricing_starts_at: t.pricing_starts_at ?? null,
          pricing_currency: t.pricing_currency,
          audience_fit: t.audience_fit as "technical" | "non_technical" | "both",
          model_provider: t.model_provider,
          open_source: t.open_source,
          self_hostable: t.self_hostable,
          api_available: t.api_available,
          founded_year: t.founded_year ?? null,
          hq_country: t.hq_country ?? null,
          hq_city: t.hq_city ?? null,
          key_strengths: [...t.key_strengths],
          status: "published",
          published_at: new Date().toISOString(),
        },
        { onConflict: "slug", ignoreDuplicates: false }
      )
      .select("id")
      .single();

    if (toolErr || !tool) {
      console.error(`\n  ✗ Failed: ${toolErr?.message}`);
      continue;
    }

    // Upsert category junction
    await supabase.from("tool_categories").upsert(
      { tool_id: tool.id, category_id: catMap[t.category_slug] },
      { onConflict: "tool_id,category_id", ignoreDuplicates: true }
    );

    // Replace content blocks (delete + insert)
    await supabase.from("content_blocks").delete().eq("tool_id", tool.id);

    const blocks = [
      { section: "overview", audience: "technical", body_md: t.overview_technical, sort_order: 0 },
      { section: "overview", audience: "non_technical", body_md: t.overview_general, sort_order: 1 },
      { section: "docs", audience: "technical", body_md: t.docs_technical, sort_order: 0 },
      { section: "docs", audience: "non_technical", body_md: t.docs_general, sort_order: 1 },
      { section: "use_cases", audience: "technical", body_md: t.use_cases_technical, sort_order: 0 },
      { section: "use_cases", audience: "non_technical", body_md: t.use_cases_general, sort_order: 1 },
    ] as const;

    await supabase.from("content_blocks").insert(
      blocks.map((block) => ({
        tool_id: tool.id,
        section: block.section,
        audience: block.audience,
        body_md: block.body_md,
        sort_order: block.sort_order,
        heading: null,
      }))
    );

    console.log("✓");
  }

  console.log("\n✅ Seeding complete!");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
