// Auto-generated by: npm run db:types
// DO NOT hand-edit. Run `npm run db:types` after any schema change.
// This is a placeholder until Supabase is running locally.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string | null;
          bio: string | null;
          avatar_url: string | null;
          is_admin: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          display_name?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          is_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      tools: {
        Row: {
          id: string;
          slug: string;
          name: string;
          tagline: string;
          website_url: string;
          logo_url: string | null;
          primary_category_id: string | null;
          pricing_tier: "free" | "freemium" | "paid" | "enterprise";
          has_free_tier: boolean;
          pricing_starts_at: number | null;
          pricing_currency: string;
          audience_fit: "technical" | "non_technical" | "both";
          model_provider: string | null;
          open_source: boolean;
          self_hostable: boolean;
          api_available: boolean;
          founded_year: number | null;
          hq_country: string | null;
          hq_city: string | null;
          key_strengths: string[];
          status: "draft" | "published" | "archived";
          submitted_by: string | null;
          edited_by_admin: boolean;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["tools"]["Row"],
          "id" | "created_at" | "updated_at"
        > &
          Partial<
            Pick<
              Database["public"]["Tables"]["tools"]["Row"],
              "id" | "created_at" | "updated_at"
            >
          >;
        Update: Partial<Database["public"]["Tables"]["tools"]["Insert"]>;
      };
      categories: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          parent_id: string | null;
          sort_order: number;
          icon: string | null;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["categories"]["Row"],
          "id" | "created_at"
        > &
          Partial<Pick<Database["public"]["Tables"]["categories"]["Row"], "id" | "created_at">>;
        Update: Partial<Database["public"]["Tables"]["categories"]["Insert"]>;
      };
      tags: {
        Row: { id: string; slug: string; name: string; created_at: string };
        Insert: Omit<Database["public"]["Tables"]["tags"]["Row"], "id" | "created_at"> &
          Partial<Pick<Database["public"]["Tables"]["tags"]["Row"], "id" | "created_at">>;
        Update: Partial<Database["public"]["Tables"]["tags"]["Insert"]>;
      };
      bookmarks: {
        Row: {
          user_id: string;
          tool_id: string;
          notes: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["bookmarks"]["Row"], "created_at"> &
          Partial<Pick<Database["public"]["Tables"]["bookmarks"]["Row"], "created_at">>;
        Update: Partial<Database["public"]["Tables"]["bookmarks"]["Insert"]>;
      };
      ratings: {
        Row: {
          id: string;
          user_id: string;
          tool_id: string;
          stars: number;
          review_text: string | null;
          status: "visible" | "hidden" | "flagged";
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["ratings"]["Row"],
          "id" | "created_at" | "updated_at"
        > &
          Partial<
            Pick<
              Database["public"]["Tables"]["ratings"]["Row"],
              "id" | "created_at" | "updated_at"
            >
          >;
        Update: Partial<Database["public"]["Tables"]["ratings"]["Insert"]>;
      };
      tool_rating_stats: {
        Row: {
          tool_id: string;
          avg_stars: number | null;
          rating_count: number;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["tool_rating_stats"]["Row"],
          "updated_at"
        > &
          Partial<Pick<Database["public"]["Tables"]["tool_rating_stats"]["Row"], "updated_at">>;
        Update: Partial<Database["public"]["Tables"]["tool_rating_stats"]["Insert"]>;
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          payload: Json;
          read_at: string | null;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["notifications"]["Row"],
          "id" | "created_at"
        > &
          Partial<Pick<Database["public"]["Tables"]["notifications"]["Row"], "id" | "created_at">>;
        Update: Partial<Database["public"]["Tables"]["notifications"]["Insert"]>;
      };
      chat_sessions: {
        Row: {
          id: string;
          user_id: string | null;
          title: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["chat_sessions"]["Row"],
          "id" | "created_at" | "updated_at"
        > &
          Partial<
            Pick<
              Database["public"]["Tables"]["chat_sessions"]["Row"],
              "id" | "created_at" | "updated_at"
            >
          >;
        Update: Partial<Database["public"]["Tables"]["chat_sessions"]["Insert"]>;
      };
      chat_messages: {
        Row: {
          id: string;
          session_id: string;
          role: "user" | "assistant";
          content: string;
          tool_citations: string[];
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["chat_messages"]["Row"],
          "id" | "created_at"
        > &
          Partial<
            Pick<Database["public"]["Tables"]["chat_messages"]["Row"], "id" | "created_at">
          >;
        Update: Partial<Database["public"]["Tables"]["chat_messages"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: {
      search_tools: {
        Args: {
          query?: string;
          cat_slugs?: string[];
          pricing_tiers?: string[];
          audiences?: string[];
          has_api?: boolean;
          open_source?: boolean;
          page_size?: number;
          page_offset?: number;
        };
        Returns: Array<{
          id: string;
          slug: string;
          name: string;
          tagline: string;
          logo_url: string | null;
          primary_category_id: string | null;
          pricing_tier: string;
          audience_fit: string;
          rank: number;
        }>;
      };
      is_admin: { Args: Record<string, never>; Returns: boolean };
    };
    Enums: Record<string, never>;
  };
};
